- name: Install nodejs
  apt: pkg=nodejs state=installed update_cache=true
- name: Install nodejs environment
  apt: pkg=nodejs-legacy state=installed update_cache=true
- name: Install npm
  apt: pkg=npm state=installed update_cache=true
